[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # HTML files should not be cached as aggressively
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # API calls to Google Sheets
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Redirect rules
[[redirects]]
  from = "/waitlist"
  to = "/#waitlist"
  status = 301

[[redirects]]
  from = "/signup"
  to = "/#waitlist"
  status = 301

[[redirects]]
  from = "/join"
  to = "/#waitlist"
  status = 301

# Form handling (backup - we're using Google Sheets)
[[redirects]]
  from = "/api/waitlist"
  to = "https://script.google.com/macros/s/AKfycbxaBCTONOEFzUDJ2FVqesQX5dxn1RlvZnAuW1jcVBh-MU2WRsWvt_-IHd7zvObOJRRNDg/exec"
  status = 200
  force = true

# 404 redirect to home
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
